apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: medicore-env-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: frontend-app
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "50m"
