apiVersion: v1
kind: Namespace
metadata:
  name: medicore-system
  labels:
    environment: local
    app.kubernetes.io/part-of: medicore
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: medicore-api
  labels:
    environment: local
    app.kubernetes.io/part-of: medicore
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: medicore-frontend
  labels:
    environment: local
    app.kubernetes.io/part-of: medicore
    app.kubernetes.io/managed-by: kustomize
