apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/namespaces
- ../../base/api-gateway
- ../../base/patient-service
- ../../base/frontend-app
- ingress.yaml

namePrefix: local-
nameSuffix: -dev

labels:
- includeSelectors: true
  pairs:
    environment: local
    cluster: medicore-dev

commonAnnotations:
  medicore.io/managed-by: kustomize
  medicore.io/environment: local

patches:
- path: patches/api-gateway-resources.yaml
- path: patches/patient-service-resources.yaml
- path: patches/frontend-app-resources.yaml

images:
- name: nginx
  newTag: alpine
