apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  namespace: medicore-env-dev
  labels:
    app.kubernetes.io/name: frontend-app
    app.kubernetes.io/component: web-ui
    app.kubernetes.io/part-of: medicore
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend-app
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
