apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/namespaces
  - ../../base/api-gateway
  - ../../base/frontend-app
  - ../../base/patient-service
  - ingress.yaml

namePrefix: aws-
nameSuffix: -prod

labels:
  - includeSelectors: true
    pairs:
      environment: prod
      cluster: medicore-prod

commonAnnotations:
  medicore.io/managed-by: kustomize
  medicore.io/environment: aws-prod

patches:
  - patch: |-
      $patch: delete
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: api-gateway-metrics
        namespace: medicore-env-dev
  - target:
      kind: ConfigMap
      name: api-config
    patch: |-
      - op: remove
        path: /data/DATABASE_URL
      - op: remove
        path: /data/POSTGRES_HOST
      - op: remove
        path: /data/POSTGRES_PORT
      - op: remove
        path: /data/POSTGRES_USER
      - op: remove
        path: /data/POSTGRES_PASSWORD
      - op: remove
        path: /data/POSTGRES_DB

images:
  - name: medicore-api
    newName: 745819688993.dkr.ecr.us-east-1.amazonaws.com/medicore-api
    newTag: latest
  - name: medicore-frontend
    newName: 745819688993.dkr.ecr.us-east-1.amazonaws.com/medicore-frontend
    newTag: latest
